[2025-05-15T15:00:00.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T14:30:00+00:00 [queued]>
[2025-05-15T15:00:00.911+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T14:30:00+00:00 [queued]>
[2025-05-15T15:00:00.911+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T15:00:00.922+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-15 14:30:00+00:00
[2025-05-15T15:00:00.931+0000] {standard_task_runner.py:60} INFO - Started process 347 to run task
[2025-05-15T15:00:00.937+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'scheduled__2025-05-15T14:30:00+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp12enwbzo']
[2025-05-15T15:00:00.940+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask parse_channel_posts
[2025-05-15T15:00:00.962+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T15:00:01.006+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T14:30:00+00:00 [running]> on host 03d8d808f3f4
[2025-05-15T15:00:01.086+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T14:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-15T14:30:00+00:00'
[2025-05-15T15:00:01.239+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-15T15:00:01.945+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/telegram_parser.py", line 272, in <module>
[2025-05-15T15:00:01.946+0000] {docker.py:429} INFO - async def parse_channel_for_day(channel_identifier: str, target_date: date):
[2025-05-15T15:00:01.946+0000] {docker.py:429} INFO - NameError: name 'date' is not defined
[2025-05-15T15:00:02.311+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-05-15T15:00:02.316+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250515T143000, start_date=20250515T150000, end_date=20250515T150002
[2025-05-15T15:00:02.336+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 132 for task parse_channel_posts (Docker container failed: {'StatusCode': 1}; 347)
[2025-05-15T15:00:02.371+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T15:00:02.400+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
