[2025-05-15T15:30:00.426+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts scheduled__2025-05-15T15:00:00+00:00 [queued]>
[2025-05-15T15:30:00.436+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts scheduled__2025-05-15T15:00:00+00:00 [queued]>
[2025-05-15T15:30:00.436+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T15:30:00.449+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-15 15:00:00+00:00
[2025-05-15T15:30:00.458+0000] {standard_task_runner.py:60} INFO - Started process 851 to run task
[2025-05-15T15:30:00.463+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1598472442', 'parse_channel_posts', 'scheduled__2025-05-15T15:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmpszx59put']
[2025-05-15T15:30:00.467+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask parse_channel_posts
[2025-05-15T15:30:00.493+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T15:30:00.541+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts scheduled__2025-05-15T15:00:00+00:00 [running]> on host 9c6602089b4d
[2025-05-15T15:30:00.631+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1598472442' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-15T15:00:00+00:00'
[2025-05-15T15:30:00.711+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-15T15:30:01.413+0000] {docker.py:429} INFO - [2025-05-15 15:30:01] [INFO] [Parser] - Запуск основного асинхронного процесса парсера...
[2025-05-15T15:30:01.414+0000] {docker.py:429} INFO - [2025-05-15 15:30:01] [INFO] [Parser] - Попытка подключения к БД (1/5): host=postgres_db dbname=parsing_results user=parser_user
[2025-05-15T15:30:09.416+0000] {docker.py:429} INFO - [2025-05-15 15:30:09] [WARNING] [Parser] - Ошибка подключения к БД: could not translate host name "postgres_db" to address: Name or service not known

[2025-05-15 15:30:09] [INFO] [Parser] - Повторная попытка через 5 секунд...
[2025-05-15T15:30:14.428+0000] {docker.py:429} INFO - [2025-05-15 15:30:14] [INFO] [Parser] - Попытка подключения к БД (2/5): host=postgres_db dbname=parsing_results user=parser_user
[2025-05-15T15:30:22.431+0000] {docker.py:429} INFO - [2025-05-15 15:30:22] [WARNING] [Parser] - Ошибка подключения к БД: could not translate host name "postgres_db" to address: Name or service not known

[2025-05-15 15:30:22] [INFO] [Parser] - Повторная попытка через 5 секунд...
[2025-05-15T15:30:27.441+0000] {docker.py:429} INFO - [2025-05-15 15:30:27] [INFO] [Parser] - Попытка подключения к БД (3/5): host=postgres_db dbname=parsing_results user=parser_user
[2025-05-15T15:30:35.461+0000] {docker.py:429} INFO - [2025-05-15 15:30:35] [WARNING] [Parser] - Ошибка подключения к БД: could not translate host name "postgres_db" to address: Temporary failure in name resolution

[2025-05-15 15:30:35] [INFO] [Parser] - Повторная попытка через 5 секунд...
[2025-05-15T15:30:40.451+0000] {docker.py:429} INFO - [2025-05-15 15:30:40] [INFO] [Parser] - Попытка подключения к БД (4/5): host=postgres_db dbname=parsing_results user=parser_user
[2025-05-15T15:30:48.469+0000] {docker.py:429} INFO - [2025-05-15 15:30:48] [WARNING] [Parser] - Ошибка подключения к БД: could not translate host name "postgres_db" to address: Temporary failure in name resolution

[2025-05-15 15:30:48] [INFO] [Parser] - Повторная попытка через 5 секунд...
[2025-05-15T15:30:53.471+0000] {docker.py:429} INFO - [2025-05-15 15:30:53] [INFO] [Parser] - Попытка подключения к БД (5/5): host=postgres_db dbname=parsing_results user=parser_user
[2025-05-15T15:31:01.490+0000] {docker.py:429} INFO - [2025-05-15 15:31:01] [WARNING] [Parser] - Ошибка подключения к БД: could not translate host name "postgres_db" to address: Name or service not known
[2025-05-15T15:31:01.492+0000] {docker.py:429} INFO - [2025-05-15 15:31:01] [ERROR] [Parser] - Превышено количество попыток подключения к БД.
[2025-05-15T15:31:01.497+0000] {docker.py:429} INFO - [2025-05-15 15:31:01] [ERROR] [Parser] - Критическая ошибка в main: Не удалось подключиться к базе данных.
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 474, in main
    raise Exception("Не удалось подключиться к базе данных.")
Exception: Не удалось подключиться к базе данных.
[2025-05-15 15:31:01] [INFO] [Parser] - Запись данных XCom в файл: /airflow/xcom/return.json
[2025-05-15T15:31:01.501+0000] {docker.py:429} INFO - [2025-05-15 15:31:01] [INFO] [Parser] - Данные XCom успешно записаны: {'channel_id': '1598472442', 'target_date_str': '2025-05-15', 'status': 'failure', 'error': 'Не удалось подключиться к базе данных.'}
[2025-05-15 15:31:01] [INFO] [Parser] - --- Скрипт парсера завершен с кодом выхода: 1 ---
[2025-05-15T15:31:01.503+0000] {docker.py:429} INFO - [2025-05-15 15:31:01] [INFO] [Parser] - Завершение работы по SystemExit с кодом 1.
[2025-05-15T15:31:02.084+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=telegram_summary_channel_1598472442, task_id=parse_channel_posts, execution_date=20250515T150000, start_date=20250515T153000, end_date=20250515T153102
[2025-05-15T15:31:02.140+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T15:31:02.170+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
