[2025-05-21T12:48:44.774+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.summarize_daily_posts scheduled__2025-05-21T12:00:00+00:00 [queued]>
[2025-05-21T12:48:44.781+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.summarize_daily_posts scheduled__2025-05-21T12:00:00+00:00 [queued]>
[2025-05-21T12:48:44.782+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-21T12:48:44.793+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): summarize_daily_posts> on 2025-05-21 12:00:00+00:00
[2025-05-21T12:48:44.802+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2025-05-21T12:48:44.806+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'summarize_daily_posts', 'scheduled__2025-05-21T12:00:00+00:00', '--job-id', '272', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp2h6c1j59']
[2025-05-21T12:48:44.809+0000] {standard_task_runner.py:88} INFO - Job 272: Subtask summarize_daily_posts
[2025-05-21T12:48:44.872+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.summarize_daily_posts scheduled__2025-05-21T12:00:00+00:00 [running]> on host 024c2995999b
[2025-05-21T12:48:44.981+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='summarize_daily_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T12:00:00+00:00'
[2025-05-21T12:48:45.045+0000] {docker.py:359} INFO - Starting docker container from image telegram_summarizer_task:latest
[2025-05-21T12:48:45.502+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Запуск основного процесса суммризатора (локальный или прямой вызов)...
[2025-05-21 12:48:45] [INFO] [Summarizer] - --- Запуск скрипта суммризации (Airflow Task) ---
[2025-05-21 12:48:45] [INFO] [Summarizer] - Попытка разбора XCom из переменной окружения 'XCOM_DATA_JSON'...
[2025-05-21 12:48:45] [INFO] [Summarizer] - Прочитаны данные XCom: channel_id=1137503644, target_date_str=2025-05-21, parser_status=success_duplicates_found
[2025-05-21 12:48:45] [WARNING] [Summarizer] - Статус предыдущей задачи парсинга: 'success_duplicates_found'. Саммаризация может быть неполной или основана на ошибочных данных.
[2025-05-21T12:48:45.515+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Успешное подключение к БД parsing_results на postgres_results_db_service:5432
[2025-05-21 12:48:45] [INFO] [Summarizer] - Проверка/создание таблицы 'summaries'...
[2025-05-21T12:48:45.517+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Таблица 'summaries' проверена/создана.
[2025-05-21 12:48:45] [INFO] [Summarizer] - Извлечение постов для channel_id=1137503644 за дату=2025-05-21 (UTC: >= 2025-05-21 00:00:00+00:00 и < 2025-05-22 00:00:00+00:00)
[2025-05-21T12:48:45.518+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Найдено 1 постов для саммаризации.
[2025-05-21 12:48:45] [INFO] [Summarizer] - Формирование промпта из 1 текстов (макс. 15)...
[2025-05-21 12:48:45] [INFO] [Summarizer] - Промпт успешно сформирован из 1 новостей.
[2025-05-21 12:48:45] [INFO] [Summarizer] - Отправка запроса к GigaChat API...
[2025-05-21T12:48:45.645+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - HTTP Request: POST https://ngw.devices.sberbank.ru:9443/api/v2/oauth "HTTP/1.1 200 OK"
[2025-05-21T12:48:45.692+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - HTTP Request: POST https://gigachat.devices.sberbank.ru/api/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
[2025-05-21T12:48:45.694+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [ERROR] [Summarizer] - Ошибка при взаимодействии с GigaChat API: (URL('https://gigachat.devices.sberbank.ru/api/v1/chat/completions'), 429, b'{"status":429,"message":"Too Many Requests"}\n', Headers({'server': 'SynGX', 'date': 'Wed, 21 May 2025 12:48:45 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '45', 'connection': 'keep-alive', 'x-request-id': 'a82d0b39-1dc5-4d58-a2b8-839cd8c07b96', 'x-session-id': '5fb03509-9329-4569-9f1f-e26a57916de4', 'allow': 'GET, POST', 'strict-transport-security': 'max-age=31536000; includeSubDomains'}))
Traceback (most recent call last):
  File "/app/summarizer.py", line 234, in get_summary_from_gigachat
    response = giga.chat(payload)
  File "/usr/local/lib/python3.9/site-packages/gigachat/client.py", line 316, in chat
    return self._decorator(lambda: post_chat.sync(self._client, chat=chat, access_token=self.token))
  File "/usr/local/lib/python3.9/site-packages/gigachat/client.py", line 260, in _decorator
    return call()
  File "/usr/local/lib/python3.9/site-packages/gigachat/client.py", line 316, in <lambda>
    return self._decorator(lambda: post_chat.sync(self._client, chat=chat, access_token=self.token))
  File "/usr/local/lib/python3.9/site-packages/gigachat/api/post_chat.py", line 34, in sync
    return build_response(response, ChatCompletion)
  File "/usr/local/lib/python3.9/site-packages/gigachat/api/utils.py", line 85, in build_response
    raise ResponseError(response.url, response.status_code, response.content, response.headers)
gigachat.exceptions.ResponseError: (URL('https://gigachat.devices.sberbank.ru/api/v1/chat/completions'), 429, b'{"status":429,"message":"Too Many Requests"}\n', Headers({'server': 'SynGX', 'date': 'Wed, 21 May 2025 12:48:45 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '45', 'connection': 'keep-alive', 'x-request-id': 'a82d0b39-1dc5-4d58-a2b8-839cd8c07b96', 'x-session-id': '5fb03509-9329-4569-9f1f-e26a57916de4', 'allow': 'GET, POST', 'strict-transport-security': 'max-age=31536000; includeSubDomains'}))
[2025-05-21 12:48:45] [ERROR] [Summarizer] - Не удалось получить саммари от LLM. Саммари за день не будет обновлено/создано.
[2025-05-21 12:48:45] [INFO] [Summarizer] - Попытка сохранения/обновления саммари для channel_id=1137503644 за дату=2025-05-21
[2025-05-21T12:48:45.699+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Саммари успешно сохранено/обновлено в БД.
[2025-05-21 12:48:45] [INFO] [Summarizer] - Соединение с БД закрыто.
[2025-05-21 12:48:45] [INFO] [Summarizer] - --- Скрипт суммризации завершен с кодом выхода: 1 ---
[2025-05-21T12:48:45.699+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Суммризатор: Перехвачен SystemExit с кодом 1. Завершение.
[2025-05-21T12:48:45.699+0000] {docker.py:429} INFO - [2025-05-21 12:48:45] [INFO] [Summarizer] - Скрипт суммризатора окончательно завершается с кодом 1 (из __main__ блока).
[2025-05-21T12:48:46.009+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-05-21T12:48:46.014+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=telegram_summary_channel_1137503644, task_id=summarize_daily_posts, execution_date=20250521T120000, start_date=20250521T124844, end_date=20250521T124846
[2025-05-21T12:48:46.041+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 272 for task summarize_daily_posts (Docker container failed: {'StatusCode': 1}; 188)
[2025-05-21T12:48:46.062+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-21T12:48:46.082+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
