[2025-05-21T11:59:51.479+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1283764331.parse_channel_posts manual__2025-05-21T11:59:50.981861+00:00 [queued]>
[2025-05-21T11:59:51.484+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1283764331.parse_channel_posts manual__2025-05-21T11:59:50.981861+00:00 [queued]>
[2025-05-21T11:59:51.484+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-21T11:59:51.491+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-21 11:59:50.981861+00:00
[2025-05-21T11:59:51.497+0000] {standard_task_runner.py:60} INFO - Started process 217 to run task
[2025-05-21T11:59:51.500+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1283764331', 'parse_channel_posts', 'manual__2025-05-21T11:59:50.981861+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp2b2zx458']
[2025-05-21T11:59:51.502+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask parse_channel_posts
[2025-05-21T11:59:51.547+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1283764331.parse_channel_posts manual__2025-05-21T11:59:50.981861+00:00 [running]> on host ef29f078a738
[2025-05-21T11:59:51.607+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1283764331' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T11:59:50.981861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T11:59:50.981861+00:00'
[2025-05-21T11:59:51.667+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-21T11:59:52.016+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Запуск основного асинхронного процесса парсера (локальный или прямой вызов)...
[2025-05-21T11:59:52.017+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - --- Запуск скрипта парсера (Airflow Task) ---
[2025-05-21 11:59:52] [INFO] [Parser] - Попытка подключения к БД (1/5): host=postgres_results_db_service port=5432 dbname=parsing_results user=parser_user
[2025-05-21T11:59:52.021+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Успешное подключение к БД!
[2025-05-21 11:59:52] [INFO] [Parser] - Проверка/создание таблицы 'telegram_messages'...
[2025-05-21T11:59:52.026+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Схема БД 'telegram_messages' проверена/обновлена.
[2025-05-21 11:59:52] [INFO] [Parser] - Инициализация Telegram клиента с сессией: /app/session/my_telegram_session
[2025-05-21T11:59:52.026+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Файл сессии '/app/session/my_telegram_session.session' существует: False
[2025-05-21T11:59:52.045+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Подключение к Telegram...
[2025-05-21T11:59:52.045+0000] {docker.py:429} INFO - [2025-05-21 11:59:52] [INFO] [Parser] - Connecting to 149.154.167.51:443/TcpFull...
[2025-05-21T11:59:53.199+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Connection to 149.154.167.51:443/TcpFull complete!
[2025-05-21T11:59:53.432+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [ERROR] [Parser] - Ошибка: Авторизация не пройдена. Файл сессии недействителен или отсутствует. Создайте его заранее.
[2025-05-21T11:59:53.433+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Disconnecting from 149.154.167.51:443/TcpFull...
[2025-05-21T11:59:53.433+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Disconnection from 149.154.167.51:443/TcpFull complete!
[2025-05-21T11:59:53.435+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [ERROR] [Parser] - Критическая ошибка в main: Не удалось инициализировать или подключиться к Telegram.
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 334, in main
    raise Exception("Не удалось инициализировать или подключиться к Telegram.")
Exception: Не удалось инициализировать или подключиться к Telegram.
[2025-05-21 11:59:53] [INFO] [Parser] - Запись данных XCom в файл: /airflow/xcom/return.json
[2025-05-21T11:59:53.436+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Создана директория для XCom: /airflow/xcom
[2025-05-21 11:59:53] [INFO] [Parser] - Данные XCom успешно записаны: {'channel_id': 1283764331, 'target_date_str': '2025-05-21', 'parsed_count': 0, 'saved_count': 0, 'skipped_because_duplicate_or_no_error': 0, 'status': 'failure', 'error_type': 'Exception', 'error_message': 'Не удалось инициализировать или подключиться к Telegram.'}
[2025-05-21 11:59:53] [INFO] [Parser] - Закрытие соединения с БД...
[2025-05-21T11:59:53.437+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Соединение с БД закрыто.
[2025-05-21T11:59:53.437+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - --- Скрипт парсера завершен с кодом выхода: 1 (XCom записан: True) ---
[2025-05-21T11:59:53.437+0000] {docker.py:429} INFO - [2025-05-21 11:59:53] [INFO] [Parser] - Перехвачен SystemExit с кодом 1. Завершение (из __main__).
[2025-05-21T11:59:53.514+0000] {docker.py:429} INFO - Python script exited with code 0
Found XCom file, outputting its content for XCom push:
[2025-05-21T11:59:53.515+0000] {docker.py:429} INFO - {
  "channel_id": 1283764331,
  "target_date_str": "2025-05-21",
  "parsed_count": 0,
  "saved_count": 0,
  "skipped_because_duplicate_or_no_error": 0,
  "status": "failure",
  "error_type": "Exception",
  "error_message": "Не удалось инициализировать или подключиться к Telegram."
}
[2025-05-21T11:59:53.755+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=telegram_summary_channel_1283764331, task_id=parse_channel_posts, execution_date=20250521T115950, start_date=20250521T115951, end_date=20250521T115953
[2025-05-21T11:59:53.804+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-21T11:59:53.828+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
