[2025-05-21T11:56:29.831+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts manual__2025-05-21T11:56:29.078468+00:00 [queued]>
[2025-05-21T11:56:29.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts manual__2025-05-21T11:56:29.078468+00:00 [queued]>
[2025-05-21T11:56:29.837+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-21T11:56:29.847+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-21 11:56:29.078468+00:00
[2025-05-21T11:56:29.851+0000] {standard_task_runner.py:60} INFO - Started process 258 to run task
[2025-05-21T11:56:29.854+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1598472442', 'parse_channel_posts', 'manual__2025-05-21T11:56:29.078468+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp8n4fizua']
[2025-05-21T11:56:29.856+0000] {standard_task_runner.py:88} INFO - Job 248: Subtask parse_channel_posts
[2025-05-21T11:56:29.892+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1598472442.parse_channel_posts manual__2025-05-21T11:56:29.078468+00:00 [running]> on host 7410cbfeba7d
[2025-05-21T11:56:29.952+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1598472442' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T11:56:29.078468+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T11:56:29.078468+00:00'
[2025-05-21T11:56:30.010+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-21T11:56:30.428+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Запуск основного асинхронного процесса парсера (локальный или прямой вызов)...
[2025-05-21T11:56:30.429+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - --- Запуск скрипта парсера (Airflow Task) ---
[2025-05-21 11:56:30] [INFO] [Parser] - Попытка подключения к БД (1/5): host=postgres_results_db_service port=5432 dbname=parsing_results user=parser_user
[2025-05-21T11:56:30.434+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Успешное подключение к БД!
[2025-05-21 11:56:30] [INFO] [Parser] - Проверка/создание таблицы 'telegram_messages'...
[2025-05-21T11:56:30.438+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Схема БД 'telegram_messages' проверена/обновлена.
[2025-05-21 11:56:30] [INFO] [Parser] - Инициализация Telegram клиента с сессией: /app/session/my_telegram_session
[2025-05-21T11:56:30.439+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Файл сессии '/app/session/my_telegram_session.session' существует: False
[2025-05-21T11:56:30.439+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [ERROR] [Parser] - Непредвиденная ошибка при инициализации Telegram клиента: invalid literal for int() with base 10: 'YOUR_TELEGRAM_API_ID'
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 151, in initialize_telegram_client
    telegram_client = TelegramClient(TELEGRAM_SESSION_PATH, int(TELEGRAM_API_ID), TELEGRAM_API_HASH)
ValueError: invalid literal for int() with base 10: 'YOUR_TELEGRAM_API_ID'
[2025-05-21T11:56:30.440+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [ERROR] [Parser] - Критическая ошибка в main: Не удалось инициализировать или подключиться к Telegram.
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 334, in main
    raise Exception("Не удалось инициализировать или подключиться к Telegram.")
Exception: Не удалось инициализировать или подключиться к Telegram.
[2025-05-21 11:56:30] [INFO] [Parser] - Запись данных XCom в файл: /airflow/xcom/return.json
[2025-05-21T11:56:30.440+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Создана директория для XCom: /airflow/xcom
[2025-05-21 11:56:30] [INFO] [Parser] - Данные XCom успешно записаны: {'channel_id': 1598472442, 'target_date_str': '2025-05-21', 'parsed_count': 0, 'saved_count': 0, 'skipped_because_duplicate_or_no_error': 0, 'status': 'failure', 'error_type': 'Exception', 'error_message': 'Не удалось инициализировать или подключиться к Telegram.'}
[2025-05-21T11:56:30.440+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Закрытие соединения с БД...
[2025-05-21T11:56:30.440+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Соединение с БД закрыто.
[2025-05-21 11:56:30] [INFO] [Parser] - --- Скрипт парсера завершен с кодом выхода: 1 (XCom записан: True) ---
[2025-05-21T11:56:30.441+0000] {docker.py:429} INFO - [2025-05-21 11:56:30] [INFO] [Parser] - Перехвачен SystemExit с кодом 1. Завершение (из __main__).
[2025-05-21T11:56:30.503+0000] {docker.py:429} INFO - Python script exited with code 0
Found XCom file, outputting its content for XCom push:
[2025-05-21T11:56:30.503+0000] {docker.py:429} INFO - {
  "channel_id": 1598472442,
  "target_date_str": "2025-05-21",
  "parsed_count": 0,
  "saved_count": 0,
  "skipped_because_duplicate_or_no_error": 0,
  "status": "failure",
  "error_type": "Exception",
  "error_message": "Не удалось инициализировать или подключиться к Telegram."
}
[2025-05-21T11:56:30.730+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=telegram_summary_channel_1598472442, task_id=parse_channel_posts, execution_date=20250521T115629, start_date=20250521T115629, end_date=20250521T115630
[2025-05-21T11:56:30.753+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-21T11:56:30.785+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
