[2025-05-15T14:11:51.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T08:30:00+00:00 [queued]>
[2025-05-15T14:11:51.568+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T08:30:00+00:00 [queued]>
[2025-05-15T14:11:51.569+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T14:11:51.582+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-15 08:30:00+00:00
[2025-05-15T14:11:51.589+0000] {standard_task_runner.py:60} INFO - Started process 181 to run task
[2025-05-15T14:11:51.598+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'scheduled__2025-05-15T08:30:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp7z0cz98z']
[2025-05-15T14:11:51.602+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask parse_channel_posts
[2025-05-15T14:11:51.627+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T14:11:51.672+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-15T08:30:00+00:00 [running]> on host 0cf936fb69ad
[2025-05-15T14:11:51.758+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-15T08:30:00+00:00'
[2025-05-15T14:11:51.862+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-15T14:11:52.325+0000] {docker.py:429} INFO - python: can't open file '/app/telegram_parser.py': [Errno 2] No such file or directory
[2025-05-15T14:11:52.713+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-05-15T14:11:52.718+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250515T083000, start_date=20250515T141151, end_date=20250515T141152
[2025-05-15T14:11:52.737+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 113 for task parse_channel_posts (Docker container failed: {'StatusCode': 2}; 181)
[2025-05-15T14:11:52.776+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T14:11:52.805+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
