[2025-05-15T14:51:29.730+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-15T14:51:29.012191+00:00 [queued]>
[2025-05-15T14:51:29.741+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-15T14:51:29.012191+00:00 [queued]>
[2025-05-15T14:51:29.741+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T14:51:29.760+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-15 14:51:29.012191+00:00
[2025-05-15T14:51:29.770+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2025-05-15T14:51:29.776+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'manual__2025-05-15T14:51:29.012191+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmpbx5kmfs_']
[2025-05-15T14:51:29.779+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask parse_channel_posts
[2025-05-15T14:51:29.809+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T14:51:29.867+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts manual__2025-05-15T14:51:29.012191+00:00 [running]> on host 03d8d808f3f4
[2025-05-15T14:51:29.980+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T14:51:29.012191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T14:51:29.012191+00:00'
[2025-05-15T14:51:30.086+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-15T14:51:30.950+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/telegram_parser.py", line 272, in <module>
    async def parse_channel_for_day(channel_identifier: str, target_date: date):
NameError: name 'date' is not defined
[2025-05-15T14:51:31.411+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-05-15T14:51:31.417+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250515T145129, start_date=20250515T145129, end_date=20250515T145131
[2025-05-15T14:51:31.441+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task parse_channel_posts (Docker container failed: {'StatusCode': 1}; 177)
[2025-05-15T14:51:31.479+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T14:51:31.504+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
