[2025-05-21T12:00:00.511+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-21T11:30:00+00:00 [queued]>
[2025-05-21T12:00:00.516+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-21T11:30:00+00:00 [queued]>
[2025-05-21T12:00:00.517+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-21T12:00:00.525+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-21 11:30:00+00:00
[2025-05-21T12:00:00.531+0000] {standard_task_runner.py:60} INFO - Started process 226 to run task
[2025-05-21T12:00:00.536+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'scheduled__2025-05-21T11:30:00+00:00', '--job-id', '258', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmpyvfvpjil']
[2025-05-21T12:00:00.539+0000] {standard_task_runner.py:88} INFO - Job 258: Subtask parse_channel_posts
[2025-05-21T12:00:00.589+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-21T11:30:00+00:00 [running]> on host ef29f078a738
[2025-05-21T12:00:00.657+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T11:30:00+00:00'
[2025-05-21T12:00:00.720+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-21T12:00:01.273+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Запуск основного асинхронного процесса парсера (локальный или прямой вызов)...
[2025-05-21T12:00:01.274+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - --- Запуск скрипта парсера (Airflow Task) ---
[2025-05-21T12:00:01.274+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Попытка подключения к БД (1/5): host=postgres_results_db_service port=5432 dbname=parsing_results user=parser_user
[2025-05-21T12:00:01.279+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Успешное подключение к БД!
[2025-05-21 12:00:01] [INFO] [Parser] - Проверка/создание таблицы 'telegram_messages'...
[2025-05-21T12:00:01.282+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Схема БД 'telegram_messages' проверена/обновлена.
[2025-05-21T12:00:01.282+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Инициализация Telegram клиента с сессией: /app/session/my_telegram_session
[2025-05-21T12:00:01.282+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Файл сессии '/app/session/my_telegram_session.session' существует: False
[2025-05-21T12:00:01.305+0000] {docker.py:429} INFO - [2025-05-21 12:00:01] [INFO] [Parser] - Подключение к Telegram...
[2025-05-21 12:00:01] [INFO] [Parser] - Connecting to 149.154.167.51:443/TcpFull...
[2025-05-21T12:00:02.575+0000] {docker.py:429} INFO - [2025-05-21 12:00:02] [INFO] [Parser] - Connection to 149.154.167.51:443/TcpFull complete!
[2025-05-21T12:00:03.030+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [ERROR] [Parser] - Ошибка: Авторизация не пройдена. Файл сессии недействителен или отсутствует. Создайте его заранее.
[2025-05-21 12:00:03] [INFO] [Parser] - Disconnecting from 149.154.167.51:443/TcpFull...
[2025-05-21T12:00:03.030+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [INFO] [Parser] - Disconnection from 149.154.167.51:443/TcpFull complete!
[2025-05-21T12:00:03.033+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [ERROR] [Parser] - Критическая ошибка в main: Не удалось инициализировать или подключиться к Telegram.
Traceback (most recent call last):
  File "/app/telegram_parser.py", line 334, in main
    raise Exception("Не удалось инициализировать или подключиться к Telegram.")
Exception: Не удалось инициализировать или подключиться к Telegram.
[2025-05-21 12:00:03] [INFO] [Parser] - Запись данных XCom в файл: /airflow/xcom/return.json
[2025-05-21T12:00:03.034+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [INFO] [Parser] - Создана директория для XCom: /airflow/xcom
[2025-05-21T12:00:03.034+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [INFO] [Parser] - Данные XCom успешно записаны: {'channel_id': 1137503644, 'target_date_str': '2025-05-21', 'parsed_count': 0, 'saved_count': 0, 'skipped_because_duplicate_or_no_error': 0, 'status': 'failure', 'error_type': 'Exception', 'error_message': 'Не удалось инициализировать или подключиться к Telegram.'}
[2025-05-21 12:00:03] [INFO] [Parser] - Закрытие соединения с БД...
[2025-05-21T12:00:03.035+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [INFO] [Parser] - Соединение с БД закрыто.
[2025-05-21 12:00:03] [INFO] [Parser] - --- Скрипт парсера завершен с кодом выхода: 1 (XCom записан: True) ---
[2025-05-21T12:00:03.035+0000] {docker.py:429} INFO - [2025-05-21 12:00:03] [INFO] [Parser] - Перехвачен SystemExit с кодом 1. Завершение (из __main__).
[2025-05-21T12:00:03.092+0000] {docker.py:429} INFO - Python script exited with code 0
[2025-05-21T12:00:03.093+0000] {docker.py:429} INFO - Found XCom file, outputting its content for XCom push:
[2025-05-21T12:00:03.094+0000] {docker.py:429} INFO - {
  "channel_id": 1137503644,
  "target_date_str": "2025-05-21",
  "parsed_count": 0,
  "saved_count": 0,
  "skipped_because_duplicate_or_no_error": 0,
  "status": "failure",
  "error_type": "Exception",
  "error_message": "Не удалось инициализировать или подключиться к Telegram."
}
[2025-05-21T12:00:03.490+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250521T113000, start_date=20250521T120000, end_date=20250521T120003
[2025-05-21T12:00:03.519+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-21T12:00:03.540+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
