[2025-05-15T08:36:22.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-14T20:00:00+00:00 [queued]>
[2025-05-15T08:36:22.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-14T20:00:00+00:00 [queued]>
[2025-05-15T08:36:22.254+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-15T08:36:22.269+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): parse_channel_posts> on 2025-05-14 20:00:00+00:00
[2025-05-15T08:36:22.276+0000] {standard_task_runner.py:60} INFO - Started process 183 to run task
[2025-05-15T08:36:22.283+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'telegram_summary_channel_1137503644', 'parse_channel_posts', 'scheduled__2025-05-14T20:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dag_generator.py', '--cfg-path', '/tmp/tmp8uhaiatz']
[2025-05-15T08:36:22.286+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask parse_channel_posts
[2025-05-15T08:36:22.305+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T08:36:22.354+0000] {task_command.py:423} INFO - Running <TaskInstance: telegram_summary_channel_1137503644.parse_channel_posts scheduled__2025-05-14T20:00:00+00:00 [running]> on host 568a8816b8e1
[2025-05-15T08:36:22.440+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='telegram_summary_channel_1137503644' AIRFLOW_CTX_TASK_ID='parse_channel_posts' AIRFLOW_CTX_EXECUTION_DATE='2025-05-14T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-14T20:00:00+00:00'
[2025-05-15T08:36:22.531+0000] {docker.py:359} INFO - Starting docker container from image telegram_parser_task:latest
[2025-05-15T08:36:23.191+0000] {docker.py:429} INFO - python: can't open file '/app/telegram_parser.py': [Errno 2] No such file or directory
[2025-05-15T08:36:24.005+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-05-15T08:36:24.010+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=telegram_summary_channel_1137503644, task_id=parse_channel_posts, execution_date=20250514T200000, start_date=20250515T083622, end_date=20250515T083624
[2025-05-15T08:36:24.035+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 102 for task parse_channel_posts (Docker container failed: {'StatusCode': 2}; 183)
[2025-05-15T08:36:24.065+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-15T08:36:24.096+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
